# Generated by Django 5.2.13 on 2026-05-02 13:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('document', models.FileField(upload_to='contracts/documents/', verbose_name='Document')),
                ('signed_at', models.DateField(verbose_name='Signed at')),
                ('valid_until', models.DateField(verbose_name='Valid until')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Amount')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='customers.customer', verbose_name='Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-signed_at', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_until__gte', models.F('signed_at'))), name='contracts_valid_until_gte_signed_at')],
            },
        ),
    ]
