# Generated by Django 5.2.13 on 2026-05-02 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('first_name', models.CharField(max_length=150, verbose_name='First name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last name')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Middle name')),
                ('phone', models.CharField(max_length=32, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='Converted at')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='advertisements.advertisement', verbose_name='Advertisement')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['last_name', 'first_name', 'pk'],
                'indexes': [models.Index(fields=['phone'], name='leads_phone_idx'), models.Index(fields=['email'], name='leads_email_idx')],
            },
        ),
    ]
