# Generated by Django 5.2.13 on 2026-05-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['last_name', 'first_name', 'pk'], 'permissions': [('convert_lead', 'Can convert lead to active customer')], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
    ]
