# Generated by Django 5.2.13 on 2026-05-04 15:07

import apps.leads.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=32, validators=[apps.leads.validators.validate_phone_number], verbose_name='Phone'),
        ),
    ]
