# Generated by Django 5.2.13 on 2026-05-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['name'], 'permissions': [('view_advertisement_statistics', 'Can view advertisement statistics')], 'verbose_name': 'Advertisement', 'verbose_name_plural': 'Advertisements'},
        ),
    ]
